name: 'Rinux'
description: 'Builds and packages using rinux'
author: 'AtomicGamer9523'
runs:
  using: 'node16'
  main: 'dist/setup/index.js'
  post: 'dist/cache-save/index.js'
  post-if: success()
branding:
  icon: 'code'
  color: 'yellow'
